field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  6c30b640-4d11-4014-859d-949e62603110:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5ee7c67e-32cf-4b9c-b3fe-a14f86f2f60c # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e2506ca-917a-44e2-aa45-f67b635a4511
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4315b9f4-bbde-4b68-8395-340ea7f8203d # Stats
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dba800c-1816-489d-8298-38ddd6c2eed8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 175280a3-b2ee-40d9-86c1-d0d481d1d81b
        userCondition: null
fields:
  5ee7c67e-32cf-4b9c-b3fe-a14f86f2f60c: # Header
    columnSuffix: tzjnqeju
    contentColumnType: text
    fieldGroup: null
    handle: statsHeader
    instructions: null
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4315b9f4-bbde-4b68-8395-340ea7f8203d: # Stats
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: stats
    instructions: null
    name: Stats
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1446020792
      columns:
        __assoc__:
          -
            - f848d360-bf9c-4006-a125-b2fc0d8f0d90 # Stat
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3686e5d4-d982-4c5e-a623-fe9f1ec6aba8 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_stats}}'
      fieldLayout: row
      maxRows: 3
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add stat'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: statGroup
name: 'Stat Group'
sortOrder: 1
