field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  6c30b640-4d11-4014-859d-949e62603110:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5ee7c67e-32cf-4b9c-b3fe-a14f86f2f60c # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e2506ca-917a-44e2-aa45-f67b635a4511
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6b6afd05-9cc6-4a8b-a9b0-426ae2ec21c5 # Stats Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56ed0697-a87d-4cee-b887-34f57e7ab412
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 175280a3-b2ee-40d9-86c1-d0d481d1d81b
        userCondition: null
fields:
  5ee7c67e-32cf-4b9c-b3fe-a14f86f2f60c: # Title
    columnSuffix: tzjnqeju
    contentColumnType: text
    fieldGroup: null
    handle: statsTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6b6afd05-9cc6-4a8b-a9b0-426ae2ec21c5: # Stats Table
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: statsList
    instructions: null
    name: 'Stats Table'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1930231651
      columns:
        __assoc__:
          -
            - 665f6825-9a80-4138-a2bf-847c424ec67b # Stat Item
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_statslist}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a stat'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: stats
name: Stats
sortOrder: 1
