field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  ad13a77e-3b93-4834-92f4-7d4bedf9c956:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 92c6dded-e3df-4ba8-a5d0-df4be7f8711f # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58f56f0c-8e7b-45d1-bf02-2fc27a264603
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53daa5c7-eeda-48f6-bd2e-616d2964bdf3 # Timeline Event
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3cc8eea-3598-4a5c-8bb9-da79130685db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 98902b30-48ff-4d62-aef6-9581d08f8c2e
        userCondition: null
fields:
  53daa5c7-eeda-48f6-bd2e-616d2964bdf3: # Timeline Event
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: timelineEvent
    instructions: null
    name: 'Timeline Event'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 2037242468
      columns:
        __assoc__:
          -
            - 29af3dd2-df2e-411f-89c9-feb3f9503bd1 # Timeline Event Pic
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a033c195-8d93-475f-afea-0a85c4653d16 # Timeline Event Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - cceaf17c-574b-47c6-b387-2466777bbdd2 # Timeline Event Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_timelineevent}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  92c6dded-e3df-4ba8-a5d0-df4be7f8711f: # Heading
    columnSuffix: ldkarart
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Title for the Timeline'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Our Story'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: timelineBlock
name: 'Timeline Block'
sortOrder: 2
