field: 8fea7832-8658-4760-82a2-fea191ae7ac0 # Blocks
fieldLayouts:
  d74ae7f2-7a10-496e-8302-4bc08a2312a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: eac87650-2610-477f-b40e-8e157361bad2 # Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27f5c25b-0241-4d6a-849a-bbb35303c256
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a1d916e1-43a1-4b87-9ee1-faa3855a7ae5
        userCondition: null
fields:
  eac87650-2610-477f-b40e-8e157361bad2: # Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: null
    name: Items
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 2016496953
      columns:
        __assoc__:
          -
            - 3ae3f06f-d2d8-4238-a143-b50ebf425c44 # styledHeading 
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - cecd596e-0f70-47f6-8809-836f4d362c13 # Heading background
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 07ab4dc1-306f-4936-9aae-0215524561cc # Heading
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 4001ac73-cfc0-4d93-83e0-3b5533db0f67 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_9_items}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add item'
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: verticalScrollingCallout
name: 'Vertical Scrolling Callout'
sortOrder: 8
