fieldLayouts:
  0973ac51-1ba7-4912-8926-f66f63840f61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5d8a60d6-f2fb-4813-acdc-dda99ff4ad46
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 093d889b-a808-46c2-9e97-68aefeef26ba
        userCondition: null
handle: image
hasTitleField: true
name: Image
section: 9dba7884-c704-4a30-ab4e-bdfbe7952faf # Hero
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
