changedFieldIndicator: 487683924
field: 53daa5c7-eeda-48f6-bd2e-616d2964bdf3 # Timeline Event
fieldLayouts:
  a58db703-ddd9-42f6-a51d-a0ffa5320bbf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 29af3dd2-df2e-411f-89c9-feb3f9503bd1 # Timeline Event Pic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ed11dab-5974-46e1-a62b-22821294765b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a033c195-8d93-475f-afea-0a85c4653d16 # Timeline Event Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d3df807-d3dd-4fe3-bb0c-b9404932c5e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cceaf17c-574b-47c6-b387-2466777bbdd2 # Timeline Event Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abd27622-2978-42de-84f8-a51b778a9506
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 879058b5-6c6a-4c46-8653-aaec2aeebaa5
        userCondition: null
fields:
  29af3dd2-df2e-411f-89c9-feb3f9503bd1: # Timeline Event Pic
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: timelineEventPic
    instructions: null
    name: 'Timeline Event Pic'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a033c195-8d93-475f-afea-0a85c4653d16: # Timeline Event Heading
    columnSuffix: afunnbsx
    contentColumnType: text
    fieldGroup: null
    handle: timelineEventHeading
    instructions: 'Big event description. e.g. We got started'
    name: 'Timeline Event Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Event in the story'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cceaf17c-574b-47c6-b387-2466777bbdd2: # Timeline Event Text
    columnSuffix: kuwpksgl
    contentColumnType: text
    fieldGroup: null
    handle: timelineEventText
    instructions: 'Put a paragraph to describe this part of the story here.'
    name: 'Timeline Event Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
