changedFieldIndicator: 1875673603
field: eac87650-2610-477f-b40e-8e157361bad2 # Items
fieldLayouts:
  fb640a1e-f926-4305-833b-ca15ea717c33:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3ae3f06f-d2d8-4238-a143-b50ebf425c44 # styledHeading 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cba64a01-1057-4f1e-877d-ce5fcdedb03d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cecd596e-0f70-47f6-8809-836f4d362c13 # Heading background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71b3f05f-f622-4ba8-8d59-51226ba9f4f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07ab4dc1-306f-4936-9aae-0215524561cc # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdfa210c-c489-4f69-81f0-49a4bf9d9d81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4001ac73-cfc0-4d93-83e0-3b5533db0f67 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 323eb9c4-b616-4e1c-bb28-844923b761e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b81d6c10-454b-4695-9d47-bcbaa6b3a45b
        userCondition: null
fields:
  3ae3f06f-d2d8-4238-a143-b50ebf425c44: # styledHeading 
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: styledheading
    instructions: null
    name: 'styledHeading '
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  07ab4dc1-306f-4936-9aae-0215524561cc: # Heading
    columnSuffix: hfewaecq
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4001ac73-cfc0-4d93-83e0-3b5533db0f67: # Text
    columnSuffix: nrjwhlwb
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: e4f4af5c-69d6-4acc-9fc4-c70666b6c415 # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  cecd596e-0f70-47f6-8809-836f4d362c13: # Heading background
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: headingBackground
    instructions: null
    name: 'Heading background'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3d5f9f28-5e41-424d-9e51-8c6791fe0561' # Public Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
