defaultPlacement: end
enableVersioning: true
handle: hero
name: Hero
propagationMethod: all
siteSettings:
  1467d9bb-2f87-4770-aa6e-91b0edc0353b: # The Invisible Man Leadership Program
    enabledByDefault: true
    hasUrls: true
    template: hero/_entry
    uriFormat: 'hero/{slug}'
type: channel
